site_name: Pokémon Automation
site_url: https://pokemon-automation.github.io
repo_url: https://github.com/PokemonAutomation/About
repo_name: PokemonAutomation/About

theme:
  logo: assets/original_logo_no_background.png
  favicon: assets/logo.png
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - search.suggest
    - search.highlight
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Getting Started: SetupGuide/index.md
  - Programs: Programs/index.md
  - Controllers: ControllerList.md
  - Discord Integration:
      - Overview: DiscordIntegration/index.md
      - Discord Bot: DiscordIntegration/DiscordBot.md
      - Discord Webhooks: DiscordIntegration/DiscordWebhooks.md
  - Developer:
      - Overview: Developer/index.md
      - Knowledge Requirement: Developer/Knowledge.md
      - How to Use Github: Developer/Git.md
      - Tutorial Button Script: Developer/TutorialMC.md
      - Tutorial Home Sorter: Developer/TutorialCC.md
     